Folder service
Navi-Cloud/Navi-Storage pull request #4
Opened 2021-09-30 14:41 UTC by 0JIEUN0

- Create new folder
- Delete folder [Recursively]

2021-09-30 23:53 UTC, KangDroid requested changes
코멘트 확인해주세요~!

2021-09-30 23:53 UTC, KangDroid commented on build.gradle.kts
> +    toolVersion = "0.8.6"
이거 0.8.7 있을건데(확인 부탁!) 그걸로 하는게 좋을거 같아요. 0.8.7에서 코틀린 1.5.x 뭐 컴파일 안되는거 고쳐졌을겁니다!

2021-09-30 23:53 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/domain/GridFSRepository.kt
> +        val fileList: List<FileObject> = gridFsTemplate.find(query).map {
이거 파일 리스트 찾는게 단순히 반환하기 위해서라면, 굳이 안해도 될거 같아요! 차라리 boolean을 반환하는게 성능상 이점이 클 것 같습니다!

2021-09-30 23:53 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/domain/GridFSRepository.kt
> +        gridFsTemplate.delete(query)
+ Recursive Delete가 안보여요...!

2021-09-30 23:53 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +    private lateinit var commonService: CommonService
일단 새로 추가하는 DI 객체는 생성자로 바꾸기로 해요!

이전에 추가되었던 건 정리하면서 다른 커밋으로 해야될 듯

2021-09-30 23:53 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        request.apply {
살짝 햇갈리는게 apply는 선언보면 request가 생성 되고 나서 람다 안에서 변경하기 위한 메소드로 기억하는데 우리는 request를 변경하는게 아니라 참조만 하기 때문에 also가 맞지 않을까요?! 혹은 with나

(개인적인 의견임다 한번 알아봐주세요!)

2021-09-30 23:53 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        request.apply {
22

2021-09-30 23:53 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        insideFiles.forEach {
아앗 이래서 find를 하고 있었군요! 전체 파일 삭제를 여기서 담당하는줄 몰랐네 ㅋㅋㅋㅋ

2021-09-30 23:53 UTC, KangDroid commented on src/test/kotlin/com/navi/storage/service/FolderServiceTest.kt
> +        gridFsTemplate.delete(Query())
Junit before / after 활용해요!

2021-10-01 03:28 UTC, 0JIEUN0 commented on build.gradle.kts
> +    toolVersion = "0.8.6"
최신이 0.8.8 이네요 그걸로 바꿀게요!

2021-10-01 03:46 UTC, 0JIEUN0 commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        request.apply {
확실히 apply 는 객체 초기화/변경 시에 주로 사용하고, also 를 내용을 변경하지 않을 때 쓰는군요
제가 apply 를 사용한 이유는 apply 가 람다 리시버를 받아서 it/this 를 쓰지 않아도 되는 점이었어요!

그러니 also 를 쓰려면 굳이 also 를 쓰지 않고 request. 로 사용하면 될 것 같아요
그렇게 변경해보겠습니다!

2021-10-01 03:48 UTC, 0JIEUN0 commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        insideFiles.forEach {
맞아요 Repository 에서는 말그대로 그 폴더 안의 내용물만 지우는거고 재귀적으로 그 폴더의 아래아래까지 지워나가는거는 FolderService 에서 담당하도록 헀어요!
폴더 내용을 검색해와서 하나하나 지우는것보다 효율적이라고 판단했습니다!

2021-10-01 03:50 UTC, 0JIEUN0 commented on src/test/kotlin/com/navi/storage/service/FolderServiceTest.kt
> +        gridFsTemplate.delete(Query())
이게 before 내에 있는 건데
before/after 활용하라는게 혹시 정확히 뭘 의미하시는 건가요??

2021-10-01 04:07 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        request.apply {
아니면 with는 어떤가요?

2021-10-01 04:09 UTC, KangDroid commented on src/test/kotlin/com/navi/storage/service/FolderServiceTest.kt
> +        gridFsTemplate.delete(Query())
에 깃헙에는 constructor 로 나와있는데 before였군요!!

2021-10-01 05:14 UTC, 0JIEUN0 commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        request.apply {
with 도 좋은데 request. 로 해보니 이것도 깔끔해보입니다! 
이 전에도 request. 으로 사용했기 때문에 이대로 가는건 어떤가요?

2021-10-01 10:00 UTC, KangDroid commented on src/main/kotlin/com/navi/storage/service/FolderService.kt
> +        request.apply {
오케이 고고~!

2021-10-01 11:18 UTC, KangDroid approved these changes

2021-10-01 11:19 UTC, merged